Jotex/Jotex/Models/ServiceViewModel.cs
using Repository.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Jotex.Models
{
    public class ServiceViewModel
    {
        public IEnumerable<Service> Services { get; set; }
        public IEnumerable<ServiceSpec> Specs { get; set; }

    }
}

Jotex/Jotex/Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Jotex.Models;
using Microsoft.AspNetCore.Mvc;
using Repository.Repositories.ContentRepositories;

namespace Jotex.Controllers
{
    public class ServiceController : Controller
    {
        private readonly IContentRepository _contentRepository;
        
        public ServiceController(IContentRepository contentRepository)
        {
           
            _contentRepository = contentRepository;
        }
        public IActionResult Index()
        {
            var model = new ServiceViewModel
            {
                Services = _contentRepository.GetServices()
            };
            return View(model);
        }
    }
}

Jotex/Jotex/ViewComponents/TestimonialViewComponent.cs
using AutoMapper;
using Jotex.Mapping;
using Jotex.Models;
using Microsoft.AspNetCore.Mvc;
using Repository.Models;
using Repository.Repositories.ContentRepositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Jotex.ViewComponents
{
    public class TestimonialViewComponent : ViewComponent
    {
        private IMapper _mapper;
        private IContentRepository _contentRepository;

        public TestimonialViewComponent(IMapper mapper,
                                IContentRepository contentRepository)
        {
            _mapper = mapper;
            _contentRepository = contentRepository;
        }

        public IViewComponentResult Invoke()
        {
            var testimonial = _contentRepository.GetTestimonials();

            var model = _mapper.Map<IEnumerable<Testimonial>, IEnumerable<TestimonialViewModel>>(testimonial);

            return View(model);
        }
    }
}

Jotex/Jotex/Views/Service/Index.cshtml
@model ServiceViewModel

@{ var a = 0;}
@{ var b = 0;}
@{ var toogle = "in active";}

@{
    ViewData["Title"] = "Xidmətlər";
}
<!-- start page-title -->
@await Html.PartialAsync("../Shared/Page/_BreadCrumb")

<!-- end page-title -->
<!-- start service-single-section -->
<section class="service-single-section section-padding">
    <div class="container">
        <div class="row">
            <div class="col col-xs-12">
                <div class="service-single-tab">
                    <ul class="nav tab-links clearfix">

                        @foreach (var item in Model.Services)
                        {

                            var id = "0";
                            a++;
                            id += a;
                            if (a == 1)
                            {
                                <li class="active">
                                    <a href="#@id" data-toggle="tab">
                                        <i class="@item.Logo"></i>
                                        <h3>@item.Name</h3>
                                    </a>
                                </li>
                            }
                            else
                            {
                                <li>
                                    <a href="#@id" data-toggle="tab">
                                        <i class="@item.Logo"></i>
                                        <h3>@item.Name</h3>
                                    </a>
                                </li>
                            }

                        }


                    </ul>

                    <div class="tab-content">
                        @foreach (var item in Model.Services)

                        {
                            var id = "0";
                            b++;
                            id += b;
                            if (b > 1)
                            {
                                toogle = "";
                            }
                            @foreach (var detail in item.Details)
                            {

                                <div class="tab-pane fade @toogle" id="@id">
                                    <div class="content-area clearfix">
                                        <div class="grid info-grid">
                                            <h3>@item.Name</h3>
                                            <p>@detail.Detail</p>
                                            <p><strong>@detail.SubDetail</strong></p>
                                            <table>
                                                <tbody>

                                                    @foreach (var spec in item.Specs)
                                                    {
                                                        <tr>
                                                            <td>@spec.Key</td>
                                                            <td>@spec.Value</td>
                                                        </tr>
                                                    }

                                                </tbody>
                                            </table>
                                        </div>
                                        <div class="grid">
                                            <img src="/images/@detail.Image" alt="Image">
                                        </div>
                                    </div>
                                    <div class="bottom-info">
                                        <div class="text">
                                            <h4>@detail.Information</h4>
                                            <p>@detail.SubDetail</p>
                                        </div>
                                        <div class="pdf-dwn-area">
                                            <a href="@detail.Document">
                                                <i class="ti-receipt"></i>
                                                <h5>@item.Name haqqında məlumat dosyası</h5>
                                                <p>Document size: 34kb</p>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="features-grid clearfix">
                                        <div class="grid">
                                            <div class="icon">
                                                <i class="fi flaticon-house"></i>
                                            </div>
                                            <h3>House protected</h3>
                                            <p>Window at the dull weather</p>
                                        </div>
                                        <div class="grid">
                                            <div class="icon">
                                                <i class="fi flaticon-umbrella-1"></i>
                                            </div>
                                            <h3>Helth protected</h3>
                                            <p>Window at the dull weather</p>
                                        </div>
                                        <div class="grid">
                                            <div class="icon">
                                                <i class="fi flaticon-cost"></i>
                                            </div>
                                            <h3>Small Premium</h3>
                                            <p>Window at the dull weather</p>
                                        </div>
                                    </div>
                                </div>
                            }}

                    </div>
                </div>
            </div>
        </div>
    </div> <!-- end container -->
</section>
<!-- end service-single-section -->
<!-- start testimonials-section-s2 -->
<section class="testimonials-section-s2 section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="section-title">
                    <span>Testimonials</span>
                    <h2>What People Says About Us</h2>
                </div>

                <div class="testimonials-s2-nav">
                    <div class="slider-s2-arrows">
                        <div class="slider-prev"><i class="fi flaticon-left-arrow-angle-big-gross-symbol"></i></div>
                        <div class="slider-next"><i class="fi flaticon-arrow-angle-pointing-to-right"></i></div>
                    </div>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="testimonials-slider-holder">
                    <div class="testimonials-slider-s2">
                        <vc:testimonial></vc:testimonial>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- end container -->
</section>
<!-- end testimonials-section-s2 -->